name: MLops-deployment
channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi
  - ipython
  - jinja2
  - joblib
  - jupyter
  - jupyterlab
  - numpy=1.23.5
  - pandas=1.5.2
  - pytest=7.2.0
  - python=3.8.15
  - scikit-learn=1.1.3
  - uvicorn=0.20.0
  - dvc=2.9.3
  - request
  - pip:
    - httpcore==0.16.2
    - httpx==0.23.1
    - rfc3986==1.5.0

